package com.peoplecore.hrm.service;

import com.peoplecore.hrm.domain.model.AttendanceRecord;
import com.peoplecore.hrm.domain.model.AttendanceRecord.AttendanceStatus;
import com.peoplecore.hrm.domain.model.Employee;
import com.peoplecore.hrm.domain.repository.AttendanceRepository;
import com.peoplecore.hrm.domain.repository.EmployeeRepository;
import com.peoplecore.hrm.exception.BusinessException;
import com.peoplecore.hrm.exception.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Attendance service — records daily attendance and produces summaries.
 *
 * <p>A {@code @Scheduled} task auto-generates attendance records at midnight
 * for all active employees (simulating a real punch-in/out integration).
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class AttendanceService {

    private final AttendanceRepository attendanceRepository;
    private final EmployeeRepository   employeeRepository;

    // ── Queries ───────────────────────────────────────────────

    public List<Map<String, Object>> getEmployeeSummary(LocalDate from, LocalDate to) {
        List<Object[]> raw = attendanceRepository.summarizeByEmployeeBetween(from, to);

        // group by employee
        Map<String, Map<String, Long>> grouped = new LinkedHashMap<>();
        for (Object[] row : raw) {
            String empId  = (String) row[0];
            String status = row[1].toString();
            Long   count  = (Long)   row[2];
            grouped.computeIfAbsent(empId, k -> new HashMap<>()).put(status, count);
        }

        return grouped.entrySet().stream().map(entry -> {
            Employee emp = employeeRepository.findById(entry.getKey())
                    .orElseThrow();
            Map<String, Object> summary = new LinkedHashMap<>();
            summary.put("empId",         emp.getId());
            summary.put("name",          emp.getFullName());
            summary.put("department",    emp.getDepartment().getName());
            summary.put("avatarInitials",emp.getAvatarInitials());
            summary.put("avatarColor",   emp.getAvatarColor());
            summary.put("present",  entry.getValue().getOrDefault("PRESENT", 0L));
            summary.put("absent",   entry.getValue().getOrDefault("ABSENT",  0L));
            summary.put("late",     entry.getValue().getOrDefault("LATE",    0L));
            summary.put("leave",    entry.getValue().getOrDefault("LEAVE",   0L));
            return summary;
        }).collect(Collectors.toList());
    }

    public List<Map<String, Object>> getRecordsForEmployee(String empId) {
        return attendanceRepository.findByEmployeeIdOrderByRecordDateDesc(empId)
                .stream()
                .map(r -> {
                    Map<String, Object> m = new LinkedHashMap<>();
                    m.put("date",     r.getRecordDate().toString());
                    m.put("status",   r.getStatus().name().toLowerCase());
                    m.put("checkIn",  r.getCheckIn());
                    m.put("checkOut", r.getCheckOut());
                    return m;
                })
                .collect(Collectors.toList());
    }

    // ── Record attendance ─────────────────────────────────────

    @Transactional
    public void markAttendance(String empId, LocalDate date, AttendanceStatus status,
                               String checkIn, String checkOut) {
        if (attendanceRepository.existsByEmployeeIdAndRecordDate(empId, date)) {
            throw new BusinessException("Attendance already recorded for " + empId + " on " + date);
        }
        Employee emp = employeeRepository.findById(empId)
                .orElseThrow(() -> new ResourceNotFoundException("Employee not found: " + empId));

        AttendanceRecord record = AttendanceRecord.builder()
                .employee(emp)
                .recordDate(date)
                .status(status)
                .checkIn(checkIn)
                .checkOut(checkOut)
                .build();

        attendanceRepository.save(record);
        log.info("Attendance recorded for {} on {} — {}", empId, date, status);
    }

    // ── Scheduled auto-generate ───────────────────────────────

    /**
     * Runs every day at 23:55 to auto-seed attendance records for active employees.
     * Simulates real-time punch-in data for demo purposes.
     * Cron: second minute hour day month weekday
     */
    @Scheduled(cron = "0 55 23 * * *")
    @Transactional
    public void autoGenerateDailyAttendance() {
        LocalDate today = LocalDate.now();
        DayOfWeek dow   = today.getDayOfWeek();

        if (dow == DayOfWeek.SATURDAY || dow == DayOfWeek.SUNDAY) {
            return; // skip weekends
        }

        Random rng = new Random();
        employeeRepository.findByStatus(Employee.EmployeeStatus.ACTIVE).forEach(emp -> {
            if (!attendanceRepository.existsByEmployeeIdAndRecordDate(emp.getId(), today)) {
                double rand = rng.nextDouble();
                AttendanceStatus status;
                String checkIn, checkOut;

                if (rand < 0.05) {
                    status   = AttendanceStatus.ABSENT;
                    checkIn  = "-";
                    checkOut = "-";
                } else if (rand < 0.12) {
                    status   = AttendanceStatus.LATE;
                    checkIn  = String.format("09:%02d AM", rng.nextInt(30) + 15);
                    checkOut = "06:00 PM";
                } else if (rand < 0.16) {
                    status   = AttendanceStatus.LEAVE;
                    checkIn  = "-";
                    checkOut = "-";
                } else {
                    status   = AttendanceStatus.PRESENT;
                    checkIn  = "09:00 AM";
                    checkOut = "06:00 PM";
                }

                AttendanceRecord record = AttendanceRecord.builder()
                        .employee(emp)
                        .recordDate(today)
                        .status(status)
                        .checkIn(checkIn)
                        .checkOut(checkOut)
                        .build();
                attendanceRepository.save(record);
            }
        });
        log.info("Auto-generated attendance records for {}", today);
    }
}
